### ISSUE TITLE
Pilot research plan

### ISSUE THREAD

**Issue by alexandralugli** [pagarme/pilot#1372]
### **Contexto**

O modelo SaaS deve representar simplicidade para os clientes e tem como objetivo conseguir trazer soluções com o mínimo de interações pessoais.

### **Objetivos**

À medida em que o conceito do produto cresceu e a maneira como os construímos mudou (divisão SaaS e PaaS), encontramos um conjunto de desafios e oportunidades para pesquisas com usuários que requer novos entendimentos e formas de trabalho.

Precisamos entender questões complexas de otimização para diferentes tipos de usuários, com diversos incentivos, necessidades e habilidades, para diminuir as incertezas no desenvolvimento, na estratégia e priorização de tarefas.

### **Questões a serem respondidas**

- Quais são as funcionalidades mais importantes para esses usuários?
- Qual é a melhor forma de apresentar dados para eles, como eles entendem melhor?
- Quais são os dados mais relevantes e quais informações eles mais procuram?
- O que os clientes gostariam que tivéssemos como serviço e não estamos atendendo?
- Quais são os fatores decisivos de escolha deles pelo Pagar.me?
- Como a nova dash os ajuda e o que precisamos mudar?
- A nova dashboard atende as necessidades dos clientes? Se não, o que temos de adicionar?

### **Hipóteses**

- Perfis iniciais:

    A. Empresa média
            A.1. Dono da empresa: Cuida do balance e coisas específicas da operação.
            A.2. Funcionários: Cuidam da área financeira e administrativa das operações.
    B. Empresa pequena
            B.1. O dono da empresa cuida de toda a operação

- Funcionalidades mais importantes:

    [A.1] Dono da empresa, empresa média
    O comportamento pode depender mais do ticket médio do que o tamanho da operação dele. Vamos puxar mais dados.

    [A.2] Funcionários, financeiro, administrativo, operação
    Normalmente, para esse cliente, o RC ensina proc v (conteúdo educacional)
    - Conciliação (extrato)
    - Verificação de payables (baixar relatórios)
    - Relatórios como dado de embasamento para projeções
    - Relacionar pedido (plataforma) com a transação
    - Checagem de status w/ lasers 

    [B.1] Dono da empresa, empresa pequena
    - Deseja saber: o quanto tem a receber / quando vai receber  / de quem vai receber
    - Agenda de recebíveis
    - Saque e manuseio
    - RAV rápido e simples (qual o set de payables?)
    - Checar status das transações
    * A visão é um pouco diferente se a empresa é tech

- O que os clientes gostariam que tivéssemos como serviço?

    [A.2] Proc v: cruzar dados - BI

### **Metodologia**

Esse conjunto de pesquisas será realizado com triangulação simultânea entre métodos quantitativos e qualitativos, bem como atitudinais e comportamentais. 

![image](https://user-images.githubusercontent.com/8549244/64790839-231fde80-d54d-11e9-8d83-79b5ea59c33a.png)
![image](https://user-images.githubusercontent.com/8549244/64790878-2f0ba080-d54d-11e9-9518-47b37cf75f78.png)

[](https://www.notion.so/d71fb9f692c84474af844137fc760d51#89c456c1f8ea476180d03e08e4e2485b)

[](https://www.notion.so/d71fb9f692c84474af844137fc760d51#c52bf6a680d74562b5f4b32724ab65ee)

**Comportamental quantitativo:**

- Análise de fluxo de cliques / intenção verdadeira: Através do FullStory e GA podemos identificar o objetivo ou a intenção dos usuários ao entrarem na dash e seu comportamento subsequente, validando se eles obtiveram sucesso em atingir seu objetivo. Identificar o funil de ações dos usuários.

**Comportamental qualitativo:**

- Teste de usabilidade moderado focado em tarefas com os usuários da dashboard atual nas telas da Pilot: Home, Extrato, Transações, Saque, Antecipação e Configurações.
    - O que vamos medir: Se o entendimento das tarefas está claro e se existem pontos de melhorias pelos viéses de arquitetura de informação, copywriting ou visual.

**Atitudinal quantitativo:**

- Formulários de pesquisa rápida: Através de e-mail ou telefone, vamos investigar aspectos gerais de expectativas e dores relacionadas à expectativas contextuais.

**Atitudinal qualitativo:**

- Feedback do cliente: Precisamos compilar os feedbacks recebidos da nova dashboard e extrair informações fornecidas sobre os top ofensores do RC/Suporte.
- Design participativo: Após coletar dados de feedback e insights suficientes, vamos chamar diferentes áreas para construir a experiência ideal de uma maneira concreta que expresse o que é mais importante para eles e por quê.

**Documentos e issues que compõe esse plano:**

- [x] Pesquisa qualitativa da home #1351 
- [x] Pesquisa quantitativa #1373
- [x] Compilado de dados e feedbacks #1377
- [x] Recrutamento de clientes #1374
- [x] Personas
- [x] Roteiro de entrevista #1375
- [x] Teste de usabilidade da Pilot #1376
