### ISSUE TITLE
Layout: Sidebar

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#171]
# Descrição
Precisamos de uma `Sidebar` para navegação entre páginas.

# Tasks - Sprint 23/10-05/11
- [ ] Menu aberto 1024px
- [ ] Menu fechado 1024px
- [ ] Menu aberto 1366px
- [ ] Menu fechado 1366px
- [ ] Menu aberto 1920px
- [ ] Menu fechado 1920px

# Exemplo

### Aberto
<img width="975" alt="captura de tela 2017-11-03 as 15 32 31" src="https://user-images.githubusercontent.com/24230714/32387654-4eeda842-c0ac-11e7-9721-6206f28db565.png">

### Fechado
<img width="635" alt="captura de tela 2017-11-03 as 15 32 41" src="https://user-images.githubusercontent.com/24230714/32387664-58aa1d34-c0ac-11e7-8a6a-122871589a31.png">

### Done: Asset no Zeplin

**Comment by flaviolee** [comment]
Comentando pra fechar a issue depois de subir o arquivo no Zeplin.
Seguem exemplos de como ficaram após as alterações.

**Abertos:**
![abertos](https://user-images.githubusercontent.com/29930809/32402923-65048bc8-c115-11e7-9666-5498b963610b.jpg)

**Fechados**
![fechados](https://user-images.githubusercontent.com/29930809/32402927-76449e96-c115-11e7-9291-a2ed3581c8be.jpg)
