### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pilot#176]
# Tasks

- [x] Definir no Zeplin os nomes corretos das cores
- [x] Adicionar blacks da sidebar @flaviolee 
- [x] ~Rever aplicações que estão com RGBA para uma cor nomeada~
- [x] Adicionar links com exemplo de aplicações das cores

**Comment by vitorvmiguel** [comment]
Agora que temos as cores finalizadas pelo @flaviolee, precisamos atualizar no componente para serem aplicadas ao projeto.

Estão atualizadas no Zeplin.

**Comment by vitorvmiguel** [comment]
Essa Issue encerra a #205 também.

**Comment by vitorvmiguel** [comment]
Label `[status] need ui` adicionado aguardando a revisão dos `hex` pela @alexandralugli

**Comment by felquis** [comment]
Coloquei os nomes das cores nos styles/colors

**Comment by felquis** [comment]
Duas observações:

1 - Há aproximadamente 25 cores no Zeplin que não estão nomeadas, preciso que sejam nomeadas o quanto antes.
2 - Quando um quadrado tem um background: green e uma opacity de 0.5. Na verdade a cor precisa ser um rgba, que é uma cor que possui opacity/alpha e elas precisam estar na folha de cores para funcionar bem.

cc @alexandralugli @flaviolee

**Comment by vitorvmiguel** [comment]
@felquis, a referência de cores é o arquivo [Cores](https://app.zeplin.io/project/59e66a0aa633e7a9cf5c0cf4/screen/59fcc95709c80de77646de57) do Zeplin, se você abrir lá todas as cores tem nomes corretos.

Os outros arquivos estão sendo atualizados para ficarem de acordo com o Styleguide que está no Zeplin.

Para efeito dessa Issue, o Styleguide do Zeplin está correto.
