### ISSUE TITLE
Layout: Modal

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#283]
# Por quê?

O componente modal necessita um padrão de estilo para desenvolvimento

## TODOS MODAIS: 
- [x] Rever títulos
- [x] Criar títulos para labels (
- [x] Rever UI mensagem de confirmação/erro (caso erro, teremos botões para voltar/fechar)
- [x] Colocar botões na tela de confirmação: (criados pela Bia)
  .copiar url do boleto
  .copiar cod da transação
  .ir para transação
  .enviar comprovante para e-mail
- [x] Prever ícone de info (?) em alguns inputs
- [x] Rever espaçamento inputs - tal como pior cenário de n. de caracteres de nome/end/email 
  (quebra de linha)
- [x] Prever senha no passo para confirmação de ação

## MODAL ADICIONAR:
- [x] Criar mais um passo e separar dados do cliente e formas de pagamento

## MODAL REPROCESSAR:
- [x] Alinhar passos a esquerda
- [x] Rever cor do valor (falar com o Lee)
- [x] Rever texto de apoio já criado pela Bia (wire)

## MODAL ESTORNAR
- [x] Rever cor do valor (falar com o Lee)

**Comment by nabuchler** [comment]
Modal reorganizar coluna no zeplin: 
[](https://zpl.io/2jZoQJr)

![screen shot 2017-11-06 at 11 33 59](https://user-images.githubusercontent.com/31291529/32443507-665e40fe-c2e6-11e7-9c50-bcf6c2b7e070.png)

**Comment by nabuchler** [comment]
@vitorvmiguel,
Turu bom? 
Precisamos mapear todos os possíveis erros nos modais de: reprocessar, adicionar e estornar transação. 
Consegue ajudar a gente com isso? :)

**Comment by nabuchler** [comment]
Fechando! 
Todo ui de modais está no Zeplin! <3 

https://zpl.io/a7G58gv
