### ISSUE TITLE
Enhancement: Estados do Botão

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#284]
# Por quê?

O componente Button necessita definição dos estados específicos.

# Tasks UI - Sprint 23/10-05/11

- [x] Definir estados do botão com aplicação das cores
- [x] Hover :hover 
- [x] Pressed :active 
- [x] Focus :focus
- [x] Clicked :visited
- [x] Subir no Zeplin

# Tasks DEV - Sprint 23/10-05/11

- [ ] Botão primário (Estados: Normal, Hover :hover, Pressed :active, Focus :focus, Clicked :visited)
- [ ] Botão secundário (Estados: Normal, Hover :hover, Pressed :active, Focus :focus, Clicked :visited)
- [ ] Botão terciário (Estados: Normal, Hover :hover, Pressed :active, Focus :focus, Clicked :visited)
- [ ] Botão com ícone (Estados: Normal, Hover :hover, Pressed :active, Focus :focus, Clicked :visited)
- [x] Tamanhos (extra-small, small, default, large) #314 

# Exemplo 

<img width="811" alt="captura de tela 2017-10-30 as 14 15 56" src="https://user-images.githubusercontent.com/24230714/32182038-ef540a20-bd7c-11e7-9901-5ff3432c48fe.png">

**Comment by flaviolee** [comment]
Pessoal, estou usando essa nomenclatura atualmente no arquivo de botões.
Ta um pouco diferente do listado acima, mas na real são as mesmas coisas.
É ok pra voces ou preferem que eu mude aqui?

![buttons](https://user-images.githubusercontent.com/29930809/31962632-d84baba2-b8dc-11e7-82a9-50159f485022.jpg)

**Comment by derekstavis** [comment]
O focused é quando tem foco com o cursor usando <kbd>Tab</kbd>?

**Comment by flaviolee** [comment]
Exato!

**Comment by derekstavis** [comment]
Nice!!

**Comment by alexandralugli** [comment]
@flaviolee Eu gostei da animação do focused, mas deixaria ele retangular porque não estamos utilizando mais nada circular :) o que acha?

**Comment by flaviolee** [comment]
Perfect. Ia rever isso contigo assim que possivel.

**Comment by mathewcst** [comment]
Não teremos um modelo pro `clicked`? É possível ter um efeito/cor/etc pra um link já clicado, é até vantajoso vendo por acessibilidade ter algo assim em botões específicos. O que acham?

**Comment by derekstavis** [comment]
O `pressed` é o `clicked`. Acho que vc se refere ao `visited` :)

**Comment by mathewcst** [comment]
iczo! Sabe tudo!

**Comment by felquis** [comment]
Para quem tem dúvidas de CSS e os estados, coloquei buttons e anchors neste codepen para servir de referencia para quem quiser https://codepen.io/felquis/pen/ZXdgYm

**Comment by darakeon** [comment]
Gente, acho que `:visited` pra botão não existe
