### ISSUE TITLE
Component: Modal

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#294]
# Por quê?
Algumas ações realizadas no pilot são realizadas por meio de Modais, para tanto é necessário um componente genérico

# Tasks - Sprint 23/10 - 05/11

- [ ] Lightbox (fundo transparente)
- [ ] Borda com dois tons (cinza/branco)
- [ ] Título com ícone
- [ ] Toolbar para botões

# Exemplo
<img width="682" alt="captura de tela 2017-10-23 as 18 53 33" src="https://user-images.githubusercontent.com/24230714/31912758-bb01fe16-b823-11e7-9f70-2c0a53643cdc.png">

**Comment by felquis** [comment]
A algum tempo eu trabalhei nessa branch https://github.com/pagarme/pilot/tree/add-modal que adiciona um modal usando dois packages, lembro que ficou com um bug no Firefox ou assim, mas funcionou muito bem! :D
