### ISSUE TITLE
Enhancement: ContextSwitch

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#298]
# Por quê?
O elemento que troca do ambiente `LIVE/TEST` necessita revisão, de posicionamento e aplicação, UI e posteriormente atualizar o código

# Tasks - Sprint 23/10-05/11
- [x] [skill] ui - Revisar layout @nabuchler @alexandralugli 
- [x] [skill] ai - Revisar posição @ericksahara @Fausto-Junior 
- [x] [skill] ai - Revisar situações bizarras (página de configurações) @ericksahara @Fausto-Junior 

# Exemplo atual
<img width="152" alt="captura de tela 2017-10-24 as 13 31 11" src="https://user-images.githubusercontent.com/24230714/31952569-abde362e-b8bf-11e7-98e2-90298e2c1671.png">

**Comment by ericksahara** [comment]
Rediscutindo a posição desse elemento com o @Fausto-Junior e @IedaOtero, achamos que faz mais sentido movê-lo para o header, pois a ideia do menu lateral é utilizarmos para itens de navegação, enquanto o header é um espaço destinado aos elementos de maior importância, num contexto mais global.

Algo assim:
http://o0wfef.axshare.com/

**Comment by vitorvmiguel** [comment]
@ericksahara tinha gostado dele no menu lateral mas sua argumentação faz sentido, entretanto esse posicionamento em termos de UI tem que ser bem pensado para não ficar estranho.

**Comment by vitorvmiguel** [comment]
Apenas para registro, o elemento `ContextSwitch` impacta nas configurações de um modo geral. Temos as configurações `globais`, `live` e `test`, e diante disso é necessário estressar além do posicionamento da chave a funcionalidade da página de configurações e feedback do contexto atual. @ericksahara @Fausto-Junior @nabuchler

**Comment by ericksahara** [comment]
@vitorvmiguel, você sabe me dizer quais configurações serão específicas para live ou test?

**Comment by LeoNero** [comment]
@vitorvmiguel Vi que vc colocou skill dev tambem... faz sentido (já que ainda falta um pouco pra chegar nessa parte no desenvolvimento)? Ou foi colocado porque quando ai e ui fizerem, a mesma issue vai ser usada pros dev?
