### ISSUE TITLE
Layout: Review Starter UI Library no Sketch

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#302]
# Por quê?
A Starter UI Library sofreu diversas alterações após as revisões de código e aplicação nas telas, elas precisam ser atualizadas no Sketch.

# Tasks 
- [x] Colors
- [x] ContextSwitch
- [x] Typography
- [x] Forms
- [x] Inputs
- [x] Aviso de ambiente teste
- [x] Tooltip
- [x] Pagination
- [x] Sidebar
- [x] Alerts (Revisar cores, principalmente roxo)
- [x] Switch
- [x] Timeline (Espaçamentos de altura)
- [x] Radio (modal adicionar transação)
- [x] Tags
- [x] TabBar (Atualizar)
- [x] Toolbar
- [x] Grid
- [x] Legend (Revisar cores e espaçamento)
- [ ] Shadow
- [ ] Loaders https://github.com/pagarme/pilot/issues/300
- [x] Date/Time Picker
- [x] Footer
- [x] Header
- [x] Avatar
- [x] Header
- [x] Table
- [x] Button (Adicionar botão cinza)
- [x] Filters
- [x] Cards (Atualizar cor do título e tamanhos de botão)

# Entregável

Styleguide de componentes no Sketch

# Exemplo ideal
Tooltip no Zeplin
<img width="660" alt="captura de tela 2017-10-24 as 13 58 30" src="https://user-images.githubusercontent.com/24230714/31954111-7839ca96-b8c3-11e7-8fb3-5e1b687010be.png">

**Comment by alexandralugli** [comment]
Categorizamos os componentes para definirmos quais deles receberão estados (hover, focus, disabled, etc) e comportamentos semelhantes. Elas foram agrupadas por similaridade de forma e/ou função e posicionamento.


Categoria 1:

[ ] Checkbox
[ ] RadioButton
[ ] Colapse
[ ] Avatar
[ ] Button Icon Only
[ ] Slider
[ ] Button - timeline


Categoria 2:

[ ] Buttons
[ ] Switch LiveTest
[ ] ToolBar Dropdown
[ ] Alert dismiss
[ ] DateTimePicker
[ ] Pagination
[ ] DatePicker - Days
[ ] Drag and Drop
[ ] Search field


Categoria 3:

[ ] Sidebar
[ ] DatePicker - Preset dates
[ ] Tabbar
[ ] Button - Text Only

**Comment by vitorvmiguel** [comment]
Itens para revisar e fechar a versão 1.0
- [ ] Inputs (detalhar aplicação de cores dos inputs no fundo preto escuro)
- [ ] Popover X Tooltip (diferenciar dois casos)
- [ ] Sidebar (saldo aberto ou fechado)

**Comment by flaviolee** [comment]
Closed issue e passa a régua. <3
