### ISSUE TITLE
Component: Pagination

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#305]
# Por quê?
As tabelas e elementos que necessitam paginação necessitam um componente para controlar a troca de páginas

# Tasks - Sprint 23/10-05/11
- [x] Interface para dev
- [x] Botões
- [x] Input de páginas digitável (texto em negrito no exemplo)
- [x] Contador de páginas

# Exemplo
<img width="463" alt="captura de tela 2017-10-24 as 14 47 55" src="https://user-images.githubusercontent.com/24230714/31956495-6102a2c4-b8ca-11e7-9161-844a89191862.png">

**Comment by LeoNero** [comment]
Algum exemplo de onde vai ser usado? Tabela de transacoes?

**Comment by vitorvmiguel** [comment]
@LeoNero exatamente! Será utilizado na tabela, exemplo:

<img width="739" alt="captura de tela 2017-10-25 as 15 45 49" src="https://user-images.githubusercontent.com/24230714/32014003-a1ac0f6e-b99b-11e7-9e88-7374b3c842bb.png">
