### ISSUE TITLE
Layout: Tela detalhe da transação

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#306]
# Por quê?
Após a revisão de arquitetura da informação com os piores cenários para casos de split/estorno/chargeback, a tela de detalhe da transação necessita os componentes de UI para desenvolvimento

# Tasks 

- [x] Simulação de transação de Boletopper
- [x] Simulação de transação a vista
- [x] Simulação dos outros estados do histórico
- [x] Verificar as datas se cabem no "Valor a receber"
- [x] Visualização dos metadados em árvore

**Comment by Fausto-Junior** [comment]
@flaviolee @vitorvmiguel tudo bem? 

Atualizei o link do protótipo com as telas de boleto pago com valor superior e inferior. 

https://b100b9.axshare.com

Vitor, depois precisamos ver alguns detalhes, quando é pago com valor inferior, qual o fluxo para que esse boleto seja pago por completo? Ainda precisamos mapear todas as saídas existentes em uma transação de boleto. 

Me chama amanhã pra fecharmos esses detalhes. 

Qualquer coisa me falem, abraços.

**Comment by flaviolee** [comment]
Telas no Zepplin (faz um tempao!)
Tinha esquecido de fechar aqui.
Thanks @vitorvmiguel que cobrou!
