### ISSUE TITLE
Component: Resumo de transações 

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#325]
### Contexto

As informações filtradas na tela de transação são exibidas no Card Resumo de transações.

### Tasks

- [ ] Contadores no subtítulo
- [ ] CardSection colapsível gráfico
- [ ] CardSection não colapsível tabela

### Exemplo

<img width="841" alt="captura de tela 2017-11-21 as 18 02 24" src="https://user-images.githubusercontent.com/24230714/33094200-7df589f0-cee6-11e7-94e9-0bdcaeee4e97.png">
