### ISSUE TITLE
Component: Sidebar

### ISSUE THREAD

**Issue by vitorvmiguel** [pagarme/pilot#343]
### Contexto

O usuário necessita navegar entre páginas.

### Requisitos

- [x] Deve exibir Logo (props para whitelabel)
- [x] Deve permitir o ícone hamburger clicável para abrir/fechar menu
- [x] Deve exibir lista de itens do menu
- [x] Deve exibir feedback visual em `hover` e `focus`
---
- [x] Interface do componente deve prever desenvolvimento em etapas
- [x] Deve exibir subitens ao clicar em item com filhos

### Exemplo

-  Aberto
<img width="1111" alt="captura de tela 2017-12-19 as 15 34 06" src="https://user-images.githubusercontent.com/24230714/34170478-25d67200-e4d2-11e7-90ac-abbf2fddc9e3.png">

- Fechado
<img width="783" alt="captura de tela 2017-12-19 as 15 34 22" src="https://user-images.githubusercontent.com/24230714/34170479-2609e400-e4d2-11e7-9397-dcf1b7fbd72c.png">

### Proposta de interface

```jsx
<Sidebar collapsed={this.state.sidebarCollapsed}>
  <SidebarHeader>
    <img src="logo" />
    <Button onClick={this.setState({ sidebarCollapsed: true })} />
  </SidebarHeader>

  <SidebarContent>
    <SegmentedSwitch onChange={environment => this.setState({ environment })} />
  </SidebarContent>

  <SidebarLink active={this.props.route === "/transactions"} icon={} title={} />

  <SidebarLink active={this.props.route === "/transactions"} icon={} title={}>
    <SidebarLink title="Pagas" onClick={} />
  </SidebarLink>

  <SidebarLink title="Nome da Empresa" subtitle="ocultar saldo">
    <Balance available={} future={} />
  </SidebarLink>
</Sidebar>

```

### Critérios de aceite

- [x] Deve exibir logo
- [x] Deve exibir menu clicável
- [x] Deve chamar a callback para página padrão ao clicar no logo
- [x] Deve exibir lista de itens
- [x] Deve exibir feedback visual em `hover` e `focus`
- [x] Deve chamar a callback para a página referente ao item clicado

_**O desenvolvimento deve considerar a interface evolutiva, porém num primeiro momento o componente não necessita de:**_
- Versão fechada
- Chave live/test
- Nome da empresa e botões Sacar/Antecipar
- Subitens
  
  
#### Dúvidas pra mandar pro pessoal de UI e depois fazer esses itens
- [x] Hover nos items
- [x] Número de opcoes dentro de opcoes
- [x] Scroll e barra de scroll
- [x] Animacao ao abrir e fechar menu
- [x] Animacao ao abrir e fechar options
- [x] O que acontece quando a pessoa clicar em live/test qd sidebar está fechada

#### TODO
- [x] Fazer html e css mais basicos
- [x] Se tiver subopcoes, mostrar seta pra baixo
- [x] Adicionar JS (logica pra mudar selected | abrir subopcoes | mudar seta ao abrir subopcoes | abrir/fechar sidebar)
- [x] Arruamar lint
- [x] Faze expandir sidebar
- [x] Passar css pra properties
- [x] Inverter seta quando abrir opcoes
- [x] Colocar label do environment qd tá collapsed
- [x] Aumentar icones do menu qd tá collapsed
- [x] Add props de tema
- [x] Fazer a key dos elementos ficar certa 
- [x] Fazer parte de mostrar mais opcoes da empresa
- [x] Ver respostas das duvidas

**Comment by LeoNero** [comment]
Esse é o mais legallllllllll

**Comment by LeoNero** [comment]
Eu e o felquis tinhamos começado por ele há um tempão quando a gente começou a ver umas parada de nova dash heheheheheh

**Comment by LeoNero** [comment]
Tem umas coisas que precisa do react-router :P tipo "Deve chamar a callback para página padrão ao clicar no logo" e "Deve chamar a callback para a página referente ao item clicado"

**Comment by derekstavis** [comment]
Faz sentido. Podemos definir isso ao modelar a interface da sidebar! Quando vcs se sentirem prontos podem chamar que a gente se reune e formata uma ideia que funcione tanto pra nossa UI Library quanto para as necessidades da nossa dashboard!

**Comment by derekstavis** [comment]
Merged in #349
